apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    field.cattle.io/creatorId: user-sfj94
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.2.34"],"port":32712,"protocol":"TCP","serviceName":"test:jenkins1-nodeport","allNodes":true}]'
  creationTimestamp: 2018-10-13T04:22:06Z
  generation: 5
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-test-jenkins1
  name: jenkins1
  namespace: test
  resourceVersion: "103239"
  selfLink: /apis/apps/v1beta2/namespaces/test/deployments/jenkins1
  uid: 8b415bd1-ce9f-11e8-b9bf-3497f6da49c5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-test-jenkins1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-10-13T04:27:25.000Z
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"jenkins1-nodeport","kind":"NodePort","name":"8080tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-test-jenkins1
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: Always
        name: jenkins1
        ports:
        - containerPort: 8080
          hostPort: 81
          name: 8080tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_home/.m2
          name: m2
        - mountPath: /usr/lib/x86_64-linux-gnu/libltdl.so.7
          name: lib
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /usr/bin/docker
          name: docker-command
        - mountPath: /etc/timezone
          name: timezone
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 999
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/hanrenwei/data/docker/var/jenkins_home
          type: ""
        name: jenkins-home
      - hostPath:
          path: /home/hanrenwei/data/.m2
          type: ""
        name: m2
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libltdl.so.7
          type: ""
        name: lib
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-sock
      - hostPath:
          path: /usr/bin/docker
          type: ""
        name: docker-command
      - hostPath:
          path: /etc/timezone
          type: ""
        name: timezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-13T04:22:17Z
    lastUpdateTime: 2018-10-13T04:22:17Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-10-13T04:22:06Z
    lastUpdateTime: 2018-10-13T04:30:07Z
    message: ReplicaSet "jenkins1-68894d795f" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1

